title: PSU CIDD Modeling/Forecasting of COVID-19 Pandemic
author:
  name: Hanks Lab, Pritchard Lab, Boni Lab [http://mol.ax]
  email: mfb9@psu.edu
description: > # this means to ignore newlines until "show_excerpts:"
  Penn State's Center for Infectious Disease Dynamics 
  modeling efforts around the coronavirus pandemic 
show_excerpts: false # set to true to show excerpts on the homepage
base_url: ""
url: "https://maciekboni.github.io"
github_username:  maciekboni

# prevent the default `home.html` layout to list posts on the homepage
list_posts_on_home: false


defaults:
  - # using post layout by default
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
  - # posts with permalink
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: "/posts/:title"
  - # pages
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"


# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"
  skin: classic

  # generate social links in footer
  # social_links:
  #   github:  "maciekboni/PSU-CIDD-COVID19/"
    # twitter: jekyllrb/
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- pages/about.md
- pages/data.md
- pages/model.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
